export const GET_MILESTONES_REQUEST = "GET_MILESTONES_REQUEST";
export const GET_MILESTONES_SUCCESS = "GET_MILESTONES_SUCCESS";
export const GET_MILESTONES_FAILURE = "GET_MILESTONES_FAILURE";

export const GET_MILESTONES_TASKS_REQUEST = "GET_MILESTONES_TASKS_REQUEST";
export const GET_MILESTONES_TASKS_SUCCESS = "GET_MILESTONES_TASKS_SUCCESS";
export const GET_MILESTONES_TASKS_FAILURE = "GET_MILESTONES_TASKS_FAILURE";

export const GET_SINGLE_MILESTONES_REQUEST = "GET_SINGLE_MILESTONES_REQUEST";
export const GET_SINGLE_MILESTONES_SUCCESS = "GET_SINGLE_MILESTONES_SUCCESS";
export const GET_SINGLE_MILESTONES_FAILURE = "GET_SINGLE_MILESTONES_FAILURE";

export const CREATE_MILESTONES_REQUEST = "CREATE_MILESTONES_REQUEST";
export const CREATE_MILESTONES_SUCCESS = "CREATE_MILESTONES_SUCCESS";
export const CREATE_MILESTONES_FAILURE = "CREATE_MILESTONES_FAILURE";


export const UPDATE_MILESTONES_REQUEST = "UPDATE_MILESTONES_REQUEST";
export const UPDATE_MILESTONES_SUCCESS = "UPDATE_MILESTONES_SUCCESS";
export const UPDATE_MILESTONES_FAILURE = "UPDATE_MILESTONES_FAILURE";

export const DELETE_MILESTONES_REQUEST = "DELETE_MILESTONES_REQUEST";
export const DELETE_MILESTONES_SUCCESS = "DELETE_MILESTONES_SUCCESS";
export const DELETE_MILESTONES_FAILURE = "DELETE_MILESTONES_FAILURE";