export const GENERAL_SETTING_REQUEST = "GENERAL_SETTING_REQUEST";
export const GENERAL_SETTING_SUCCESS = "GENERAL_SETTING_SUCCESS";
export const GENERAL_SETTING_FAILURE = "GENERAL_SETTING_FAILURE";

export const CREATE_DYNAMIC_FIELD_REQUEST = "CREATE_DYNAMIC_FIELD_REQUEST";
export const CREATE_DYNAMIC_FIELD_SUCCESS = "CREATE_DYNAMIC_FIELD_SUCCESS";
export const CREATE_DYNAMIC_FIELD_FAILURE = "CREATE_DYNAMIC_FIELD_FAILURE";

export const GET_DYNAMIC_FIELD_REQUEST = "GET_DYNAMIC_FIELD_REQUEST";
export const GET_DYNAMIC_FIELD_SUCCESS = "GET_DYNAMIC_FIELD_SUCCESS";
export const GET_DYNAMIC_FIELD_FAILURE = "GET_DYNAMIC_FIELD_FAILURE";

export const UPDATE_DYNAMIC_FIELD_REQUEST = "UPDATE_DYNAMIC_FIELD_REQUEST";
export const UPDATE_DYNAMIC_FIELD_SUCCESS = "UPDATE_DYNAMIC_FIELD_SUCCESS";
export const UPDATE_DYNAMIC_FIELD_FAILURE = "UPDATE_DYNAMIC_FIELD_FAILURE";

export const DELETE_DYNAMIC_FIELD_REQUEST = "DELETE_DYNAMIC_FIELD_REQUEST";
export const DELETE_DYNAMIC_FIELD_SUCCESS = "DELETE_DYNAMIC_FIELD_SUCCESS";
export const DELETE_DYNAMIC_FIELD_FAILURE = "DELETE_DYNAMIC_FIELD_FAILURE";

export const CREATE_DYNAMIC_REPORT_REQUEST = "CREATE_DYNAMIC_REPORT_REQUEST";
export const CREATE_DYNAMIC_REPORT_SUCCESS = "CREATE_DYNAMIC_REPORT_SUCCESS";
export const CREATE_DYNAMIC_REPORT_FAILURE = "CREATE_DYNAMIC_REPORT_FAILURE";

export const GET_DYNAMIC_REPORT_REQUEST = "GET_DYNAMIC_REPORT_REQUEST";
export const GET_DYNAMIC_REPORT_SUCCESS = "GET_DYNAMIC_REPORT_SUCCESS";
export const GET_DYNAMIC_REPORT_FAILURE = "GET_DYNAMIC_REPORT_FAILURE";

export const UPDATE_DYNAMIC_REPORT_REQUEST = "UPDATE_DYNAMIC_REPORT_REQUEST";
export const UPDATE_DYNAMIC_REPORT_SUCCESS = "UPDATE_DYNAMIC_REPORT_SUCCESS";
export const UPDATE_DYNAMIC_REPORT_FAILURE = "UPDATE_DYNAMIC_REPORT_FAILURE";

export const DELETE_DYNAMIC_REPORT_REQUEST = "DELETE_DYNAMIC_REPORT_REQUEST";
export const DELETE_DYNAMIC_REPORT_SUCCESS = "DELETE_DYNAMIC_REPORT_SUCCESS";
export const DELETE_DYNAMIC_REPORT_FAILURE = "DELETE_DYNAMIC_REPORT_FAILURE";