export const GENERAL_SETTING_REQUEST = "GENERAL_SETTING_REQUEST";
export const GENERAL_SETTING_SUCCESS = "GENERAL_SETTING_SUCCESS";
export const GENERAL_SETTING_FAILURE = "GENERAL_SETTING_FAILURE";

export const CREATE_OPERATIONS_REQUEST = "CREATE_DYNAMIC_FIELD_REQUEST";
export const CREATE_DYNAMIC_FIELD_SUCCESS = "CREATE_DYNAMIC_FIELD_SUCCESS";
export const CREATE_DYNAMIC_FIELD_FAILURE = "CREATE_DYNAMIC_FIELD_FAILURE";

export const GET_OPERATIONS_REQUEST = "GETOPERATIONS_REQUEST";
export const GETOPERATIONS_SUCCESS = "GETOPERATIONS_SUCCESS";
export const GETOPERATIONS_FAILURE = "GETOPERATIONS_FAILURE";

export const GET_REPORT_TYPE_REQUEST = "GET_REPORT_TYPE_REQUEST";
export const GET_REPORT_TYPE_SUCCESS = "GET_REPORT_TYPE_SUCCESS";
export const GET_REPORT_TYPE_FAILURE = "GET_REPORT_TYPE_FAILURE";

export const UPDATE_DYNAMIC_REPORT_REQUEST = "UPDATE_DYNAMIC_REPORT_REQUEST";
export const UPDATE_DYNAMIC_REPORT_SUCCESS = "UPDATE_DYNAMIC_REPORT_SUCCESS";
export const UPDATE_DYNAMIC_REPORT_FAILURE = "UPDATE_DYNAMIC_REPORT_FAILURE";

export const DELETE_DYNAMIC_REPORT_REQUEST = "DELETE_DYNAMIC_REPORT_REQUEST";
export const DELETE_DYNAMIC_REPORT_SUCCESS = "DELETE_DYNAMIC_REPORT_SUCCESS";
export const DELETE_DYNAMIC_REPORT_FAILURE = "DELETE_DYNAMIC_REPORT_FAILURE";