export const GET_ACTIVITIES_REQUEST = "GET_ACTIVITIES_REQUEST";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";
export const GET_ACTIVITIES_FAILURE = "GET_ACTIVITIES_FAILURE";

export const GET_SINGLE_ACTIVITY_REQUEST = "GET_SINGLE_ACTIVITY_REQUEST";
export const GET_SINGLE_ACTIVITY_SUCCESS = "GET_SINGLE_ACTIVITY_SUCCESS";
export const GET_SINGLE_ACTIVITY_FAILURE = "GET_SINGLE_ACTIVITY_FAILURE";

export const CREATE_ACTIVITIES_REQUEST = "CREATE_ACTIVITIES_REQUEST";
export const CREATE_ACTIVITIES_SUCCESS = "CREATE_ACTIVITIES_SUCCESS";
export const CREATE_ACTIVITIES_FAILURE = "CREATE_ACTIVITIES_FAILURE";


export const UPDATE_ACTIVITIES_REQUEST = "UPDATE_ACTIVITIES_REQUEST";
export const UPDATE_ACTIVITIES_SUCCESS = "UPDATE_ACTIVITIES_SUCCESS";
export const UPDATE_ACTIVITIES_FAILURE = "UPDATE_ACTIVITIES_FAILURE";

export const DELETE_ACTIVITIES_REQUEST = "DELETE_ACTIVITIES_REQUEST";
export const DELETE_ACTIVITIES_SUCCESS = "DELETE_ACTIVITIES_SUCCESS";
export const DELETE_ACTIVITIES_FAILURE = "DELETE_ACTIVITIES_FAILURE";